# Generated by Django 3.1 on 2020-08-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='branch',
            field=models.CharField(default='', max_length=70),
        ),
    ]
