# Generated by Django 3.1 on 2020-08-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_product_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
